name: LearningSteps Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name acrwesteu

    - name: Build Docker image
      run: |
        docker build -t acrwesteu.azurecr.io/learningsteps-api:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push acrwesteu.azurecr.io/learningsteps-api:${{ github.sha }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: rg-dev-aks
        cluster-name: aks-west-eu

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/learningsteps-api \
        learningsteps-api=acrwesteu.azurecr.io/learningsteps-api:${{ github.sha }}

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/learningsteps-api
        kubectl get pods -o wide